In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
from IPython.display import Image
import numpy as np
import pandas as pd
import seaborn as sns
import warnings

# warning 무시
warnings.filterwarnings('ignore')

# e notation 표현 방식 변경
pd.options.display.float_format = '{:.2f}'.format

# 모든 컬럼 표시
pd.set_option('display.max_columns', None)

In [3]:
iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0          5.10         3.50          1.40         0.20  setosa
1          4.90         3.00          1.40         0.20  setosa
2          4.70         3.20          1.30         0.20  setosa
3          4.60         3.10          1.50         0.20  setosa
4          5.00         3.60          1.40         0.20  setosa

In [4]:
iris['sepal']= iris['sepal_length']*iris['sepal_width']
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species  sepal
0          5.10         3.50          1.40         0.20  setosa  17.85
1          4.90         3.00          1.40         0.20  setosa  14.70
2          4.70         3.20          1.30         0.20  setosa  15.04
3          4.60         3.10          1.50         0.20  setosa  14.26
4          5.00         3.60          1.40         0.20  setosa  18.00

In [5]:
iris = iris.drop(['petal_length','petal_width'], axis=1)
iris.head()

   sepal_length  sepal_width species  sepal
0          5.10         3.50  setosa  17.85
1          4.90         3.00  setosa  14.70
2          4.70         3.20  setosa  15.04
3          4.60         3.10  setosa  14.26
4          5.00         3.60  setosa  18.00

In [6]:
iris.loc[iris['species']== 'setosa'].sort_values('sepal',ascending=False).head(10)

    sepal_length  sepal_width species  sepal
15          5.70         4.40  setosa  25.08
14          5.80         4.00  setosa  23.20
33          5.50         4.20  setosa  23.10
18          5.70         3.80  setosa  21.66
32          5.20         4.10  setosa  21.32
5           5.40         3.90  setosa  21.06
16          5.40         3.90  setosa  21.06
10          5.40         3.70  setosa  19.98
48          5.30         3.70  setosa  19.61
46          5.10         3.80  setosa  19.38

In [7]:
!pip install opendata-kr -q

from opendata import dataset

dataset.download('서울시자전거')

[서버] Jaen
======= 다운로드 시작 =======

data/서울시자전거/seoul_bicycle.csv

  0%|          | 0.00/31.1M [00:00<?, ?B/s]

======= 다운로드 완료 =======

In [8]:
df2= pd.read_csv('data/서울시자전거/seoul_bicycle.csv')
df2.head()

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리,이용시간
0,Jan-20-2020,3,중랑센터,일일(회원),M,AGE_003,3,61.82,0.52,2230.00,75
1,Jan-20-2020,3,중랑센터,일일(회원),M,AGE_004,1,39.62,0.28,1220.00,15
2,Jan-20-2020,3,중랑센터,정기,M,AGE_005,3,430.85,4.01,17270.00,53
3,Jan-20-2020,5,상암센터 정비실,일일(회원),\N,AGE_005,2,1.79,0.02,90.00,33
4,Jan-20-2020,5,상암센터 정비실,정기,F,AGE_003,1,4501.96,45.47,196010.00,64

In [9]:
df2['대여일자'] = pd.to_datetime(df2['대여일자'])
df2['연도'] = df2['대여일자'].dt.year
df2['월'] = df2['대여일자'].dt.month
df2['일'] = df2['대여일자'].dt.day
df2['요일'] = df2['대여일자'].dt.dayofweek
df2.head()

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리,이용시간,연도,월,일,요일
0,2020-01-20,3,중랑센터,일일(회원),M,AGE_003,3,61.82,0.52,2230.00,75,2020,1,20,0
1,2020-01-20,3,중랑센터,일일(회원),M,AGE_004,1,39.62,0.28,1220.00,15,2020,1,20,0
2,2020-01-20,3,중랑센터,정기,M,AGE_005,3,430.85,4.01,17270.00,53,2020,1,20,0
3,2020-01-20,5,상암센터 정비실,일일(회원),\N,AGE_005,2,1.79,0.02,90.00,33,2020,1,20,0
4,2020-01-20,5,상암센터 정비실,정기,F,AGE_003,1,4501.96,45.47,196010.00,64,2020,1,20,0

In [10]:
sample = sns.load_dataset('titanic')
sample.head(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.00,1,0,7.25,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.00,1,0,71.28,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.00,0,0,7.92,S,Third,woman,False,NaN,Southampton,yes,True

In [11]:
sample['age_bin'] = pd.cut(sample['age'], [0, 15, 30, 45, sample['age'].max()])
sample['age_bin'].value_counts()

age_bin
(15.0, 30.0]    326
(30.0, 45.0]    202
(45.0, 80.0]    103
(0.0, 15.0]      83
Name: count, dtype: int64

In [12]:
sample['age_qbin'] = pd.qcut(sample['age'], 3, labels=['young', 'normal', 'old'])
sample['age_qbin'].value_counts()

age_qbin
young     246
old       236
normal    232
Name: count, dtype: int64